[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction/=lib/account-abstraction/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Fork testing configuration
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# Profile for fork testing
[profile.fork]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction/=lib/account-abstraction/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.20"
# Fork from latest block by default
fork_block_number = 0
# Speed up tests
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
